/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_clouderhem_executor_Executor */

#ifndef _Included_io_github_clouderhem_executor_Executor
#define _Included_io_github_clouderhem_executor_Executor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_clouderhem_executor_Executor
 * Method:    run
 * Signature: (Lio/github/clouderhem/executor/Params;)Lio/github/clouderhem/executor/Result;
 */
JNIEXPORT jobject JNICALL Java_io_github_clouderhem_executor_Executor_run
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
