/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lc_Executor */

#ifndef _Included_com_lc_Executor
#define _Included_com_lc_Executor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lc_Executor
 * Method:    run
 * Signature: (Lcom/lc/Params;)Lcom/lc/Result;
 */
JNIEXPORT jobject JNICALL Java_com_lc_Executor_run
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
